org: pauloimb
service: api-alumnos

provider:
  name: aws
  runtime: python3.12
  timeout: 30  
  iam:
    role: arn:aws:iam::670692919870:role/LabRole

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    events:
      - http:
          path: /alumnos/listar
          method: post
          cors: true
          integration: lambda
  buscar:
    handler: Lambda_BuscarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/buscar
          method: post
          cors: true
          integration: lambda
  crear:
    handler: Lambda_CrearAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/crear
          method: post
          cors: true
          integration: lambda
  eliminar:
    handler: Lambda_EliminarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/eliminar
          method: delete
          cors: true
          integration: lambda
  modificar:
    handler: Lambda_ModificarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/modificar
          method: put
          cors: true
          integration: lambda

